### ISSUE TITLE
Exe version

### ISSUE THREAD

**Issue by gitihobo** [JoeyStrandnes/DFDNet-SimpleGUI#1]
I dont run poweshell scripts, is it possible to get an exe version of this awesome project?

**Comment by JoeyStrandnes** [comment]
Glad you find this project useful!
The main reason for writing this program in power shell is the fact that anybody can view/inspect the source code and be sure that nothing fishy is going on. A compiled exe version would be less transparent.
Why would a compiled exe version of the script be any different to the regular script?

GitHub does not allow me to attach an exe file to this comment, so you’ll have to make one on your own. This can be done very easily with the [PS2EXE](https://github.com/MScholtes/PS2EXE) tool and the following command. 

Open PowerShell in the same folder as the DFDNetGUI.ps1 script and type the following. 
`Install-Module ps2exe`
`Invoke-ps2exe .\DFDNetGUI.ps1 .\DFDNetGUI.exe`
Now you should have a compiled exe version of the PowerShell script.

Hope it helps.

**Comment by gitihobo** [comment]
The thing is Poweshell is disabled for security reasons in my pcs is it not possible to put it in the assets section? I want to use it but I cant change these settings because Im not the admin

**Comment by JoeyStrandnes** [comment]
Hi, 

I updated the latest release to contain the compiled EXE version of this project ([Release 1.2](https://github.com/JoeyStrandnes/DFDNet-SimpleGUI/releases/tag/v1.2))

Regards
Joseph

**Comment by gitihobo** [comment]
Thank you so much thats awesome
